#!/bin/bash
# docker.sh — Docker Compose stack generation and management

DOCKER_OUTPUT_DIR="${SCRIPT_DIR}/docker-output"

# --- Prerequisites ---

_check_docker_prerequisites() {
    log_info "Checking Docker prerequisites..."
    if ! command -v docker &>/dev/null; then
        log_error "Docker is not installed. Install Docker first: https://docs.docker.com/get-docker/"
        exit 1
    fi
    if ! docker compose version &>/dev/null; then
        log_error "Docker Compose plugin not found. Install it: https://docs.docker.com/compose/install/"
        exit 1
    fi
    if ! docker info &>/dev/null; then
        log_error "Docker daemon is not running. Start Docker first."
        exit 1
    fi
    log_success "Docker prerequisites met."
}

# --- File Generators ---

_generate_env_file() {
    local env_file="${DOCKER_OUTPUT_DIR}/.env"
    log_info "Generating .env file..."

    local db_root_pass db_name db_user db_pass pma_pass
    db_root_pass=$(generate_password)
    db_name="app_db"
    db_user="app_user"
    db_pass=$(generate_password)
    pma_pass=$(generate_password)

    # Save credentials for later reference
    save_credential "mariadb_root_password" "$db_root_pass"
    save_credential "mariadb_app_user" "$db_user"
    save_credential "mariadb_app_password" "$db_pass"

    # Determine primary PHP version (highest)
    local primary_php
    IFS=',' read -ra _php_arr <<< "$CFG_PHP_VERSIONS"
    primary_php="${_php_arr[-1]}"

    cat > "$env_file" <<EOF
# Generated by server-setup — Docker environment
# Do not commit this file to version control.

# PHP
PHP_VERSION=${primary_php}

# MariaDB
MARIADB_ROOT_PASSWORD=${db_root_pass}
MARIADB_DATABASE=${db_name}
MARIADB_USER=${db_user}
MARIADB_PASSWORD=${db_pass}

# Web server
WEB_SERVER=${CFG_WEB_SERVER}

# Ports
HTTP_PORT=80
HTTPS_PORT=443
PMA_PORT=8080
DB_PORT=3306
REDIS_PORT=6379
ES_PORT=9200
NODE_PORT=3000

# phpMyAdmin
PMA_BLOWFISH_SECRET=${pma_pass}

# Node.js
NODEJS_VERSION=${CFG_NODEJS_VERSION}
EOF

    chmod 600 "$env_file"
    log_success "Generated: .env"
}

_generate_php_dockerfile() {
    local version="$1"
    local dir="${DOCKER_OUTPUT_DIR}/php"
    mkdir -p "$dir"

    local dockerfile="${dir}/Dockerfile.${version}"
    log_info "Generating PHP ${version} Dockerfile..."

    cat > "$dockerfile" <<'DEOF'
ARG PHP_VERSION
FROM php:${PHP_VERSION}-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    libpng-dev libjpeg-dev libfreetype6-dev libxml2-dev libzip-dev \
    libldap2-dev libbz2-dev libcurl4-openssl-dev libpq-dev \
    libxslt1-dev libc-client-dev libkrb5-dev libicu-dev \
    libonig-dev unzip curl \
    && rm -rf /var/lib/apt/lists/*

DEOF

    # Build extension install commands from configured extensions
    local ext_install=()
    local pecl_install=()
    IFS=',' read -ra exts <<< "$CFG_PHP_EXTENSIONS"
    for ext in "${exts[@]}"; do
        ext=$(echo "$ext" | xargs)
        case "$ext" in
            fpm|cli|cgi) continue ;;  # not installable extensions
            gd)
                echo 'RUN docker-php-ext-configure gd --with-freetype --with-jpeg \' >> "$dockerfile"
                echo '    && docker-php-ext-install gd' >> "$dockerfile"
                ;;
            ldap)
                echo 'RUN docker-php-ext-configure ldap \' >> "$dockerfile"
                echo '    && docker-php-ext-install ldap' >> "$dockerfile"
                ;;
            imap)
                echo 'RUN docker-php-ext-configure imap --with-kerberos --with-imap-ssl \' >> "$dockerfile"
                echo '    && docker-php-ext-install imap' >> "$dockerfile"
                ;;
            apcu)
                pecl_install+=("apcu")
                ;;
            opcache|bcmath|xml|mysql|mysqli|pdo_mysql|zip|intl|bz2|curl|mbstring|pgsql|soap|xsl)
                ext_install+=("$ext")
                ;;
            mysql)
                # Map generic 'mysql' to mysqli + pdo_mysql
                ext_install+=("mysqli" "pdo_mysql")
                ;;
            *)
                ext_install+=("$ext")
                ;;
        esac
    done

    # Deduplicate ext_install
    local -A seen_exts
    local unique_exts=()
    for e in "${ext_install[@]}"; do
        if [[ -z "${seen_exts[$e]:-}" ]]; then
            seen_exts[$e]=1
            unique_exts+=("$e")
        fi
    done

    if [[ ${#unique_exts[@]} -gt 0 ]]; then
        echo "" >> "$dockerfile"
        echo "RUN docker-php-ext-install ${unique_exts[*]}" >> "$dockerfile"
    fi

    if [[ ${#pecl_install[@]} -gt 0 ]]; then
        echo "" >> "$dockerfile"
        for pecl_ext in "${pecl_install[@]}"; do
            echo "RUN pecl install ${pecl_ext} && docker-php-ext-enable ${pecl_ext}" >> "$dockerfile"
        done
    fi

    # Composer (if enabled)
    if [[ "${CFG_INSTALL_COMPOSER,,}" == "yes" ]]; then
        echo "" >> "$dockerfile"
        echo "COPY --from=composer:latest /usr/bin/composer /usr/bin/composer" >> "$dockerfile"
    fi

    echo "" >> "$dockerfile"
    echo "WORKDIR /var/www/html" >> "$dockerfile"

    log_success "Generated: php/Dockerfile.${version}"
}

_generate_nginx_conf() {
    local dir="${DOCKER_OUTPUT_DIR}/nginx"
    mkdir -p "$dir"

    local primary_php
    IFS=',' read -ra _php_arr <<< "$CFG_PHP_VERSIONS"
    primary_php="${_php_arr[-1]}"
    local fpm_service="php-${primary_php//\./-}-fpm"

    cat > "${dir}/default.conf" <<EOF
server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php index.html;

    location / {
        try_files \$uri \$uri/ /index.php?\$query_string;
    }

    location ~ \.php\$ {
        fastcgi_pass ${fpm_service}:9000;
        fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\.ht {
        deny all;
    }
EOF

    if [[ "${CFG_INSTALL_PHPMYADMIN,,}" == "yes" ]]; then
        cat >> "${dir}/default.conf" <<'EOF'

    location /phpmyadmin/ {
        proxy_pass http://phpmyadmin:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
EOF
    fi

    echo "}" >> "${dir}/default.conf"

    log_success "Generated: nginx/default.conf"
}

_generate_apache_conf() {
    local dir="${DOCKER_OUTPUT_DIR}/apache"
    mkdir -p "$dir"

    local primary_php
    IFS=',' read -ra _php_arr <<< "$CFG_PHP_VERSIONS"
    primary_php="${_php_arr[-1]}"
    local fpm_service="php-${primary_php//\./-}-fpm"

    cat > "${dir}/httpd-vhost.conf" <<EOF
<VirtualHost *:80>
    ServerName localhost
    DocumentRoot /var/www/html

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>

    <FilesMatch \.php\$>
        SetHandler "proxy:fcgi://${fpm_service}:9000"
    </FilesMatch>
EOF

    if [[ "${CFG_INSTALL_PHPMYADMIN,,}" == "yes" ]]; then
        cat >> "${dir}/httpd-vhost.conf" <<'EOF'

    ProxyPass /phpmyadmin http://phpmyadmin:80/
    ProxyPassReverse /phpmyadmin http://phpmyadmin:80/
EOF
    fi

    echo "</VirtualHost>" >> "${dir}/httpd-vhost.conf"

    log_success "Generated: apache/httpd-vhost.conf"
}

_generate_phpmyadmin_config() {
    local dir="${DOCKER_OUTPUT_DIR}/config"
    mkdir -p "$dir"

    cat > "${dir}/phpmyadmin.config.inc.php" <<'EOF'
<?php
$cfg['blowfish_secret'] = getenv('PMA_BLOWFISH_SECRET') ?: 'change-me-to-a-random-string';
$cfg['Servers'][1]['host'] = 'mariadb';
$cfg['Servers'][1]['port'] = '3306';
$cfg['Servers'][1]['auth_type'] = 'cookie';
$cfg['Servers'][1]['compress'] = false;
$cfg['Servers'][1]['AllowNoPassword'] = false;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
EOF

    log_success "Generated: config/phpmyadmin.config.inc.php"
}

_generate_docker_compose() {
    local compose_file="${DOCKER_OUTPUT_DIR}/docker-compose.yml"
    log_info "Generating docker-compose.yml..."

    # Start compose file
    cat > "$compose_file" <<'EOF'
# Generated by server-setup
# Manage with: docker compose up -d / down / restart

services:
EOF

    # PHP-FPM services (one per version)
    IFS=',' read -ra php_versions <<< "$CFG_PHP_VERSIONS"
    local primary_php="${php_versions[-1]}"

    for ver in "${php_versions[@]}"; do
        ver=$(echo "$ver" | xargs)
        local svc_name="php-${ver//\./-}-fpm"
        cat >> "$compose_file" <<EOF

  ${svc_name}:
    build:
      context: ./php
      dockerfile: Dockerfile.${ver}
      args:
        PHP_VERSION: "${ver}"
    volumes:
      - webroot:/var/www/html
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - backend
EOF
    done

    # Web server
    if [[ "${CFG_WEB_SERVER,,}" == "nginx" ]]; then
        cat >> "$compose_file" <<EOF

  nginx:
    image: nginx:alpine
    ports:
      - "\${HTTP_PORT:-80}:80"
      - "\${HTTPS_PORT:-443}:443"
    volumes:
      - webroot:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    depends_on:
EOF
        for ver in "${php_versions[@]}"; do
            ver=$(echo "$ver" | xargs)
            echo "      - php-${ver//\./-}-fpm" >> "$compose_file"
        done
        cat >> "$compose_file" <<EOF
    networks:
      - frontend
      - backend
EOF
    else
        cat >> "$compose_file" <<EOF

  apache:
    image: httpd:alpine
    ports:
      - "\${HTTP_PORT:-80}:80"
      - "\${HTTPS_PORT:-443}:443"
    volumes:
      - webroot:/var/www/html:ro
      - ./apache/httpd-vhost.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf:ro
    restart: unless-stopped
    depends_on:
EOF
        for ver in "${php_versions[@]}"; do
            ver=$(echo "$ver" | xargs)
            echo "      - php-${ver//\./-}-fpm" >> "$compose_file"
        done
        cat >> "$compose_file" <<EOF
    networks:
      - frontend
      - backend
EOF
    fi

    # MariaDB
    cat >> "$compose_file" <<'EOF'

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - dbdata:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend
EOF

    # phpMyAdmin (conditional)
    if [[ "${CFG_INSTALL_PHPMYADMIN,,}" == "yes" ]]; then
        cat >> "$compose_file" <<'EOF'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
      BLOWFISH_SECRET: ${PMA_BLOWFISH_SECRET}
    ports:
      - "${PMA_PORT:-8080}:80"
    volumes:
      - ./config/phpmyadmin.config.inc.php:/etc/phpmyadmin/config.user.inc.php:ro
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - backend
EOF
    fi

    # Redis (conditional)
    if [[ "${CFG_INSTALL_REDIS,,}" == "yes" ]]; then
        cat >> "$compose_file" <<'EOF'

  redis:
    image: redis:alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data
    restart: unless-stopped
    networks:
      - backend
EOF
    fi

    # Elasticsearch (conditional)
    if [[ "${CFG_INSTALL_ELASTICSEARCH,,}" == "yes" ]]; then
        cat >> "$compose_file" <<'EOF'

  elasticsearch:
    image: elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${ES_PORT:-9200}:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    restart: unless-stopped
    networks:
      - backend
EOF
    fi

    # Node.js (conditional)
    if [[ "${CFG_INSTALL_NODEJS,,}" == "yes" ]]; then
        cat >> "$compose_file" <<EOF

  node:
    image: node:${CFG_NODEJS_VERSION}-alpine
    working_dir: /app
    volumes:
      - nodeapp:/app
    ports:
      - "\${NODE_PORT:-3000}:3000"
    command: ["node", "-e", "console.log('Node.js ready'); setTimeout(() => {}, 2147483647)"]
    restart: unless-stopped
    networks:
      - backend
EOF
    fi

    # Volumes
    cat >> "$compose_file" <<'EOF'

volumes:
  webroot:
  dbdata:
EOF

    if [[ "${CFG_INSTALL_REDIS,,}" == "yes" ]]; then
        echo "  redisdata:" >> "$compose_file"
    fi
    if [[ "${CFG_INSTALL_ELASTICSEARCH,,}" == "yes" ]]; then
        echo "  esdata:" >> "$compose_file"
    fi
    if [[ "${CFG_INSTALL_NODEJS,,}" == "yes" ]]; then
        echo "  nodeapp:" >> "$compose_file"
    fi

    # Networks
    cat >> "$compose_file" <<'EOF'

networks:
  frontend:
  backend:
EOF

    log_success "Generated: docker-compose.yml"
}

_docker_compose_up() {
    log_info "Starting Docker Compose stack..."
    run_cmd docker compose -f "${DOCKER_OUTPUT_DIR}/docker-compose.yml" \
        --env-file "${DOCKER_OUTPUT_DIR}/.env" up -d --build

    if [[ "$SS_DRY_RUN" != "true" ]]; then
        log_info "Waiting for services to become healthy..."
        local retries=30
        while [[ $retries -gt 0 ]]; do
            if docker compose -f "${DOCKER_OUTPUT_DIR}/docker-compose.yml" ps --format json 2>/dev/null | \
               grep -q '"Health":"healthy"' 2>/dev/null || \
               docker compose -f "${DOCKER_OUTPUT_DIR}/docker-compose.yml" ps 2>/dev/null | grep -q "healthy"; then
                break
            fi
            sleep 2
            retries=$((retries - 1))
        done

        log_info "Service status:"
        docker compose -f "${DOCKER_OUTPUT_DIR}/docker-compose.yml" ps
    fi
}

# --- Main Entry Point ---

install_docker_stack() {
    log_info "=== Docker Compose Installation ==="

    if [[ "$SS_DRY_RUN" != "true" ]]; then
        _check_docker_prerequisites
    else
        log_info "[DRY RUN] Would check Docker prerequisites"
    fi

    # Create output directory
    mkdir -p "$DOCKER_OUTPUT_DIR"
    log_info "Output directory: $DOCKER_OUTPUT_DIR"

    # Generate all configuration files
    _generate_env_file
    _generate_docker_compose

    # PHP Dockerfiles (one per version)
    IFS=',' read -ra _versions <<< "$CFG_PHP_VERSIONS"
    for ver in "${_versions[@]}"; do
        ver=$(echo "$ver" | xargs)
        _generate_php_dockerfile "$ver"
    done

    # Web server config
    if [[ "${CFG_WEB_SERVER,,}" == "nginx" ]]; then
        _generate_nginx_conf
    else
        _generate_apache_conf
    fi

    # phpMyAdmin config
    if [[ "${CFG_INSTALL_PHPMYADMIN,,}" == "yes" ]]; then
        _generate_phpmyadmin_config
    fi

    # Create default index.php in webroot placeholder
    mkdir -p "${DOCKER_OUTPUT_DIR}/html"
    cat > "${DOCKER_OUTPUT_DIR}/html/index.php" <<'EOF'
<?php phpinfo();
EOF

    # Save state
    save_state "install_method" "docker"
    save_state "docker_output_dir" "$DOCKER_OUTPUT_DIR"
    mark_step_completed "docker"

    # Start the stack
    _docker_compose_up

    # Summary
    echo ""
    log_success "============================================"
    log_success "  Docker Stack Ready!"
    log_success "============================================"
    echo ""
    log_info "Output directory:  $DOCKER_OUTPUT_DIR"
    log_info "Web server:        ${CFG_WEB_SERVER} on http://localhost"
    log_info "MariaDB:           localhost:3306"
    if [[ "${CFG_INSTALL_PHPMYADMIN,,}" == "yes" ]]; then
        log_info "phpMyAdmin:        http://localhost:8080"
    fi
    if [[ "${CFG_INSTALL_REDIS,,}" == "yes" ]]; then
        log_info "Redis:             localhost:6379"
    fi
    if [[ "${CFG_INSTALL_ELASTICSEARCH,,}" == "yes" ]]; then
        log_info "Elasticsearch:     http://localhost:9200"
    fi
    log_info "Credentials:       $SS_CREDENTIALS_FILE"
    echo ""
    log_info "Manage with:"
    log_info "  sudo ./server-setup.sh --start"
    log_info "  sudo ./server-setup.sh --stop"
    log_info "  sudo ./server-setup.sh --restart"
    echo ""
}

# --- Lifecycle ---

docker_lifecycle() {
    local action="$1"
    local compose_dir="$DOCKER_OUTPUT_DIR"

    # Try to load from state if default doesn't exist
    if [[ ! -f "${compose_dir}/docker-compose.yml" ]]; then
        local saved_dir
        saved_dir=$(load_state "docker_output_dir")
        if [[ -n "$saved_dir" && -f "${saved_dir}/docker-compose.yml" ]]; then
            compose_dir="$saved_dir"
        else
            log_error "No Docker Compose stack found. Run with --docker first."
            exit 1
        fi
    fi

    local compose_file="${compose_dir}/docker-compose.yml"
    local env_file="${compose_dir}/.env"

    case "$action" in
        start)
            log_info "Starting Docker Compose stack..."
            run_cmd docker compose -f "$compose_file" --env-file "$env_file" up -d
            ;;
        stop)
            log_info "Stopping Docker Compose stack..."
            run_cmd docker compose -f "$compose_file" --env-file "$env_file" down
            ;;
        restart)
            log_info "Restarting Docker Compose stack..."
            run_cmd docker compose -f "$compose_file" --env-file "$env_file" restart
            ;;
    esac

    if [[ "$SS_DRY_RUN" != "true" ]]; then
        log_info "Service status:"
        docker compose -f "$compose_file" ps 2>/dev/null || true
    fi
}
